/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/
// Copyright 2017-2023 NXP
// All rights reserved.
#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define PCR_IBE_ibe1 0x01u /*!<@brief Input Buffer Enable: Enables */

/*! @name FC4_P0 (coord A1), P1_8
  @{ */
/* @} */

/*! @name FC4_P1 (coord B1), P1_9
  @{ */
/* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitDEBUG_UARTPins(void);

/*! @name SWCLK (coord A16), P0_1/SWCLK/U8[4]
  @{ */
/* @} */

/*! @name SWDIO (coord A17), P0_0/SWDIO/U8[16]
  @{ */
/* @} */

/*! @name SWO (coord B16), P0_2/SWO/U8[12]
  @{ */
/* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitSWD_DEBUGPins(void);

/*! @name PIO3_2 (coord D15), P3_2/LED_GREEN/Q8[5]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITLEDSPINS_LED_GREEN_GPIO GPIO3 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITLEDSPINS_LED_GREEN_GPIO_PIN 2U /*!<@brief GPIO pin number */
#define BOARD_INITLEDSPINS_LED_GREEN_GPIO_PIN_MASK (1U << 2U) /*!<@brief GPIO pin mask */
/* @} */

/*! @name PIO3_3 (coord D16), P3_3/LED_BLUE/Q9[2]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITLEDSPINS_LED_BLUE_GPIO GPIO3 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITLEDSPINS_LED_BLUE_GPIO_PIN 3U /*!<@brief GPIO pin number */
#define BOARD_INITLEDSPINS_LED_BLUE_GPIO_PIN_MASK (1U << 3U) /*!<@brief GPIO pin mask */
/* @} */

/*! @name PIO3_4 (coord F14), P3_4/LED_RED/J5/Q8[2]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITLEDSPINS_LED_RED_GPIO GPIO3 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITLEDSPINS_LED_RED_GPIO_PIN 4U /*!<@brief GPIO pin number */
#define BOARD_INITLEDSPINS_LED_RED_GPIO_PIN_MASK (1U << 4U) /*!<@brief GPIO pin mask */
/* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitLEDsPins(void);

/*! @name PIO0_6 (coord C14), P0_6
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITBUTTONSPINS_SW3_GPIO GPIO0 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITBUTTONSPINS_SW3_GPIO_PIN 6U /*!<@brief GPIO pin number */
#define BOARD_INITBUTTONSPINS_SW3_GPIO_PIN_MASK (1U << 6U) /*!<@brief GPIO pin mask */
/* @} */

/*! @name PIO0_29 (coord F8), P0_29
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITBUTTONSPINS_SW2_GPIO GPIO0 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITBUTTONSPINS_SW2_GPIO_PIN 29U /*!<@brief GPIO pin number */
#define BOARD_INITBUTTONSPINS_SW2_GPIO_PIN_MASK (1U << 29U) /*!<@brief GPIO pin mask */
/* @} */

/*! @name PIO1_11 (coord D3), P1_11
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITBUTTONSPINS_SW4_GPIO GPIO1 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITBUTTONSPINS_SW4_GPIO_PIN 11U /*!<@brief GPIO pin number */
#define BOARD_INITBUTTONSPINS_SW4_GPIO_PIN_MASK (1U << 11U) /*!<@brief GPIO pin mask */
/* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitBUTTONsPins(void);

#define PCR_IBE_ibe1 0x01u /*!<@brief Input Buffer Enable: Enables */
#define PCR_PE_pe1 0x01u   /*!<@brief Pull Enable: Enables */
#define PCR_PS_ps1 0x01u   /*!<@brief Pull Select: Enables internal pullup resistor */
#define PCR_SRE_sre1 0x01u /*!<@brief Slew Rate Enable: Slow */

/*! @name PIO0_7 (coord C13), P0_7
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITLCDFXIOPINS_LCD_RS_GPIO GPIO0 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITLCDFXIOPINS_LCD_RS_GPIO_PIN 7U /*!<@brief GPIO pin number */
#define BOARD_INITLCDFXIOPINS_LCD_RS_GPIO_PIN_MASK (1U << 7U) /*!<@brief GPIO pin mask */
/* @} */

/*! @name PIO0_12 (coord D11), P0_12/FXIO_LCD_CS/J35[9]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITLCDFXIOPINS_LCD_CS_GPIO GPIO0 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITLCDFXIOPINS_LCD_CS_GPIO_PIN 12U /*!<@brief GPIO pin number */
#define BOARD_INITLCDFXIOPINS_LCD_CS_GPIO_PIN_MASK (1U << 12U) /*!<@brief GPIO pin mask */
/* @} */

/*! @name PIO1_11 (coord D3), P1_11
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITLCDFXIOPINS_LCD_BLK_GPIO GPIO4 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITLCDFXIOPINS_LCD_BLK_GPIO_PIN 5U /*!<@brief GPIO pin number */
#define BOARD_INITLCDFXIOPINS_LCD_BLK_GPIO_PIN_MASK (1U << 5U) /*!<@brief GPIO pin mask */
/* @} */

/*! @name PIO4_7 (coord T4), P4_7
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITLCDFXIOPINS_LCD_RST_GPIO GPIO4 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITLCDFXIOPINS_LCD_RST_GPIO_PIN 7U /*!<@brief GPIO pin number */
#define BOARD_INITLCDFXIOPINS_LCD_RST_GPIO_PIN_MASK (1U << 7U) /*!<@brief GPIO pin mask */
/* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitLCDFXIOPins(void);

#define PCR_IBE_ibe1 0x01u /*!<@brief Input Buffer Enable: Enables */
#define PCR_PE_pe1 0x01u   /*!<@brief Pull Enable: Enables */
#define PCR_PS_ps0 0x00u   /*!<@brief Pull Select: Enables internal pulldown resistor */

/*! @name PIO4_6 (coord N7), P4_6/MIKROE_INT/J38[2]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITLCDTPPINS_LCD_INT_GPIO GPIO4 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITLCDTPPINS_LCD_INT_GPIO_PIN 6U /*!<@brief GPIO pin number */
#define BOARD_INITLCDTPPINS_LCD_INT_GPIO_PIN_MASK (1U << 6U) /*!<@brief GPIO pin mask */
/* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitLCDTPPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
